version: '3.7'
services:
    server:
        container_name: 'react_monitor_server'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment:
            - NODE_ENV=development
        command: ["npm", "run", "dev-server"]

    client:
        container_name: 'react_monitor_client'
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        command: ["npm", "run", "dev-client"]
